spring.application.name=merchant-service
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/free
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.username=system
spring.datasource.password=Utkarsh2001
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
